### ISSUE TITLE
Relicense does not have permission from all contributors

### ISSUE THREAD

**Issue by unascribed** [TridentMC/Smores#1]
You do not have permission from all the contributors to https://github.com/elytra/Smores and therefore you cannot legally relicense this project to the Apache 2.0 from the MIT License. You will have to get permission or declare that the Apache 2.0 only applies to contributions by those who have agreed, making an MIT/Apache mixed license project.

See also: TridentMC/Union#1. This repo has the same issues.

**Comment by CalmBit** [comment]
I am the sole code contributor to Smores, as far as I can tell. I forked this repository from the commit _before_ your fix. If anyone else has any code they've put into Smores, I'll be sure to re-implement it to satisfy the license requirements.

**Comment by unascribed** [comment]
Well, it's hard to tell that, because you sort of clobbered the history.

All the textures are Falkreon's, at the very least.

**Comment by CalmBit** [comment]
The textures can be removed, although it's dubious whether or not they're affected by licensing. I can do a thorough blame and go from there if that would be satisfactory.

**Comment by unascribed** [comment]
It's not dubious. All of the resources are covered by the license.

Can we discuss this through some medium that isn't GitHub issues?

**Comment by CalmBit** [comment]
A quick check over of the commit I forked from (see https://github.com/elytra/Smores/commit/350202bb9646802f0c22cebed00a1b86dbabdd58) shows that the only other person who committed code was Falkreon, and their code was eliminated during the two major refactors of the primary codebase. In this way, the code is 100% my contribution, and able to be relicensed. I admit, it was extremely bad form to include the assets from the original project, and I'll remove them straight away. Thank you for bringing it to my attention!

**Comment by CalmBit** [comment]
As of the most recent commit, the resources have been removed, and from my end it would seem as if there's no longer any license violations. Sorry to cause you all trouble with this.
